name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}   
          script: |
            rm -rf ~/flask-rag-api
            git clone https://github.com/diyadave/flask_rag_apikey.git
            cd flask-rag-api
            docker stop flask-rag-api || true
            docker rm flask-rag-api || true
            docker build -t flask-rag-api .
            docker run -d -p 5007:5000 --name flask-rag-api flask-rag-api
